# -*- mode: ruby -*-
# vi: set ft=ruby :
# Midonet allinone deployment. It is based on puppetlabs/openstack
# allinone example: https://github.com/puppetlabs/puppetlabs-openstack/blob/master/manifests/role/allinone.pp
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
# require 'vagrant-openstack-provider'
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box       = 'allinone'
  config.ssh.username = 'centos'
  config.vm.hostname  = "allinone"
  config.vm.provider :openstack do |os|
    os.meta_args_support  = true
    os.openstack_auth_url = 'http://118.67.110.147:5000/v2.0/tokens'
    os.username           = 'alejandro'
    os.password           = 'hWKhHUfkmYFxCu3G'
    os.tenant_name        = 'alejandro'
    os.flavor             = 'm2.huge'
    os.image              = 'CentOS7 - notty'
    os.networks           = [ 'alejandro-private', 'bgp1-network' ]
    os.floating_ip_pool   = 'external'
  end
  config.vm.define "allinone" do |allinone|
    allinone.vm.synced_folder ".", "/vagrant"
    allinone.vm.synced_folder "../..", "/openstack"
    allinone.vm.synced_folder "/home/alex/Workspace/puppet-midonet", "/ali-g"
    allinone.vm.provision :shell, path: "run_allinone_centos.sh", args:['@@ssh_ip@@']
  end
end
