# -*- mode: ruby -*-
# vi: set ft=ruby :
# Midonet allinone deployment. It is based on puppetlabs/openstack
# allinone example: https://github.com/puppetlabs/puppetlabs-openstack/blob/master/manifests/role/allinone.pp

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.username = 'ubuntu'
  config.vm.hostname  = "allinone"
  config.vm.provider :openstack do |os|
    os.meta_args_support  = true
    os.openstack_auth_url = 'http://118.67.110.147:5000/v2.0/tokens'
    os.username           = 'alex.ruiz'
    os.password           = 'midonia'
    os.tenant_name        = 'AlexRuiz'
    os.flavor             = 'm2.xlarge'
    os.image              = 'Ubuntu16-prereqs'
    os.networks           = [ {
      name: 'Internal-ahharu',
      address: '192.168.1.5'
      },{
        name: 'BGPnetwork'
        }]
    os.floating_ip_pool   = 'external'
    os.floating_ip        = '119.15.124.176'
  end
  config.vm.define "controller" do |allinone|
    allinone.vm.synced_folder ".", "/vagrant"
    allinone.vm.synced_folder "../../", "/openstack"
    allinone.vm.synced_folder "/home/ahharu/puppet-work/puppet-midonet", "/ali-g"
    allinone.vm.provision :shell, path: "run_allinone_ubuntu.sh", args:['192.168.1.5','@@ssh_ip@@']
  end

end
